/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002109",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#6bff8f",
        "on-primary-fixed-variant": "#005321",
        "on-primary-container": "#004b1e",
        "inverse-surface": "#25342a",
        "surface-container-low": "#e6f8ea",
        "secondary": "#934b1b",
        "tertiary": "#795900",
        "tertiary-container": "#d8a41c",
        "on-background": "#101f16",
        "inverse-on-surface": "#e3f5e7",
        "on-secondary": "#ffffff",
        "surface-container": "#e0f2e4",
        "inverse-primary": "#4ae176",
        "secondary-container": "#ffa26b",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#753403",
        "on-secondary-fixed": "#331200",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdbc9",
        "surface-dim": "#cdded1",
        "surface-tint": "#006e2f",
        "outline": "#6d7b6c",
        "on-tertiary-container": "#533c00",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#f6be39",
        "tertiary-fixed": "#ffdfa0",
        "surface": "#ecfef0",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#5c4300",
        "secondary-fixed-dim": "#ffb68d",
        "primary-container": "#22c55e",
        "surface-container-highest": "#d5e7d9",
        "on-secondary-container": "#783605",
        "surface-bright": "#ecfef0",
        "primary-fixed-dim": "#4ae176",
        "on-primary": "#ffffff",
        "surface-container-high": "#dbeddf",
        "background": "#ecfef0",
        "on-tertiary-fixed": "#261a00",
        "primary": "#006e2f",
        "on-surface-variant": "#3d4a3d",
        "surface-variant": "#d5e7d9",
        "outline-variant": "#bccbb9",
        "on-surface": "#101f16"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1.0rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "xl": "40px",
        "container-max": "1200px",
        "md": "16px",
        "lg": "24px",
        "base": "4px",
        "sm": "8px",
        "gutter": "16px"
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
